---
title: Blog Post 5
author: Transformers
date: '2022-11-09'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-11-09T07:38:30-04:00'
featuredVideo: ~
featuredImage: ~
---

#Blog Post 5 Prompt
One of the requirements for your project is that you bring together multiple datasets to enable a more in depth analysis. This could be including weather data based on dates, including demographic data based on location, among many other possibilities.
For this week’s blog post, please describe the datasets you are combining, how you are combining them, and what your initial findings were. Also, were there any difficulties in combining the data? If you haven’t finished combining datasets, that is fine, just discuss where you are in the process and what your next steps are.

```{r}
suppressPackageStartupMessages(library(tidyverse))
load("../../../dataset/abortionDataClean.RData")
load("../../../dataset/MaxStateAff.RData")

abortionDataClean %>% 
  group_by(state) %>% 
  summarise(AverageAbortionRate = mean(AbortionRate, na.rm=TRUE)) %>%
  inner_join(MaxStateAff) %>% 
  ggplot() + 
  stat_summary(aes(x = reorder(state, AverageAbortionRate), y = AverageAbortionRate, fill = as.factor(Affiliation)), geom = "bar") + 
  coord_flip() + 
  scale_fill_viridis_d(option = "cividis") + 
  labs(title = 'Average Abortion Rate by State Affiliation', x = 'State\n', y = '\nAverage Abortion Rate', fill = "Affliation") + 
  ggthemes::theme_economist() +
  theme(axis.text.y = element_text(size = 7), axis.title = element_text(size = 10),legend.position = 'right', legend.text = element_text(size = 8))
```

The dataset that we combined with out original dataset is about the state level constituency returns for U.S. presidential elections from 1976 to 2020. With this dataset, we created a new State Affiliation data set with two columns, one for state abbreviations and the second for political affiliation(Democrat, Republican, or Divided). In order to combine this new dataset with our original one, we used a join with the shared state column and used this new dataset of three columns, state, average abortion rate, and affiliation, to create the plot above.
From the plot, we see some differences in affiliation of some states from the plot that we created in last week's post. These states being: Neveda, Florida, Michigan, Pennsylvania, North Carolina, Colorado, Ohio, Iowa, and Wisconsin.