---
title: Blog Post 3
author: Transformers
date: '2022-10-28'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-28T11:28:05-04:00'
featuredVideo: ~
featuredImage: ~
---

Our group goal is to choose a dataset that allows us to answer social justice questions related to a topic we care about, but since we are still deciding between two vastly different topic areas, we explored 4 datasets (instead of 3) from distinct sources, with 2 datasets that compile information related to homelessness in the US, and 2 datasets that compile information related to pregnancies/abortions in the US.


Homelessness

1. https://www.huduser.gov/portal/sites/default/files/xls/2007-2021-HIC-Counts-by-State.xlsx
https://www.huduser.gov/portal/sites/default/files/xls/2007-2021-PIT-Counts-by-State.xlsx 
This dataset has the state-wise distribution of data regarding homelessness in the United States. This dataset is available on the website of the Department of Housing and Urban Development. Interestingly, the point in time count is conducted by local homeslessness planning bodies that apply for grants from the Department of Housing and Urban Development (HUD) and coordinate homelessness services. In this dataset, we can find data for the years 2007-2021. There are 58 rows and 77 columns of data for each year. The dataset has detailed information about types of shelters available in that particular state. Then, there are specific columns about each shelter type (beds/units with children, DV and non DV beds, dedicated beds for youth and veterans). This dataset also provides information about age, gender and race of homeless individuals. It also has information about the number of beds provided by Homelessness Management Information System for each shelter type. I'd like to answer these questions: What kind of shelters are needed more? What are the demographics of people in shelters like permanent housing? How is it different from those in other types of shelters? I'd also like to see how these numbers changed during COVID. However, as this dataset only has information up till 2021, I won't be able to see the impact of opening up after the pandemic.

2. https://data.chhs.ca.gov/dataset/11c64371-5d52-4d08-831a-e553528e661f/resource/e5b00c34-dabf-44c5-b274-afd249a859aa/download/hospital-encounters-for-homeless-patients-zfh7ur.zip
These datasets are collected and provided by CHHS, California Health and Human Services Open Data. It is a combined dataset. The main dataset is the data of 2019-2020 homeless hospital encounters in California with reported age, race, and sex, expected payer by facility. This dataset has 25450 rows and 16 columns. It also includes the name, location, ownership and systems of the facilities, and teaching, med cares, demographics of the people. The other datasets are much shorter, and complement the main dataset. One (18 rows and 4 columns) includes a description, name, and type of the field title. One dataset (35 rows and 6 columns) includes encounter type, demographics, years and homelessness number. The last file is a description of the “statewide” dataset. I am able to load the main dataset. I want to investigate questions related to the relationship among the age, healthcare with facilities (ownerships) and location. Is there a pattern among the location of the cities within California that relates to the homelessness numbers and demographic data we have. One problem we may encounter is that we are not as familiar with the information that is specific to California (facilities, differences among cities, the healthcare system, etc). 

Abortion

3. https://osf.io/dwyms
There are 524715 rows and 17 columns in this data set. This data was aggregated by one individual, Caitilin Myers into her own ‘Myers Abortion Database’. Myers collected her data from a variety of sources including, public advertisement for all types of facilities, state-licensing databases, ‘current facility and historical versions of facility websites’ including Planned Parenthood, current and historical directories of “providers that are members of the National Abortion Federal (NAF)”, news accounts of some facilities, “ periodic surveys of appointment availability at providers conducted by [her] research team beginning in March 2022”, ‘information from organizations with political agendas to corroborate primary sources or fill in information I cannot find elsewhere’, abortiondocs.org, National Abortion Federation database, and sometimes LifeDynamics. There is not too much that needs to be cleaned with this data, but there are a couple ways that we can modify it to meet our needs better. The ‘monthlydate’, ‘year’, and ‘month’ columns can be changed to one singular date column. Some interesting columns are ‘dest_loc_type’, ‘distance_origintodest’, ‘distance_type’, and ‘dest_asp’. The main questions are: What is the current state of how accessible abortion clinics are for people in different states? What is the furthest an individual has to travel in order to find a clinic? Are there any trends in areas where they are not easily accessible? Has there been a change in proximity over the years? (Have more clinics been brought up? Have less?) Some challenges I can foresee are trying to make the information easy to understand because there is a lot of use of codes to represent geographic locations rather than names, and visualizing locations. It would be great if we could represent the data as a map rather than the data visualizations we have used so far.

4. https://osf.io/td7mk: More details regarding the dataset can be found here: https://osf.io/kthnf/
This dataset is by the Guttmacher Institute, a policy institution focused on “advancing sexual and reproductive health and rights (SRHR) worldwide.” [1] It displays data related to pregnancies, births, abortions and miscarriages for each state in the United States from 1988 to 2017. There are 912 rows and 50 columns in this dataset. For each row (observation), the state, year, and statistics for the various age groups are given. For each age group, there is statistics for pregnancy rate, abortion rate, birth rate, abortion ratio (Number of abortions per 1000 births), number of pregnancies, miscarriages, abortions, births and the population of women. The age groups of the women are as follows: less than 15, 15 - 17, 18 - 19, 15  - 19, less than 20, 20 - 24, 25 - 29, 30 - 34, 35 - 29 and 40 plus. The data was originally collected because the Guttmacher Institute believed that “ Documenting pregnancy, birth and abortion rates over time and by age-group helps illustrate broadly how people’s reproductive lives have changed over the past four decades.” [2] The counts of births by age were obtained from the National Center for Health Statistics, which “provides annual counts of births in the United States, as compiled in the National Vital Statistics System from data derived from birth certificates.” [2] The counts of abortions by state were from the Guttmacher Institute’s “periodic national Abortion Provider Census.” [2],  Centers for Disease Control and Prevention Abortion Surveillance Reports and data from state health departments [3]. The population of women was obtained from the Census Bureau [3].
Loading the data was not a problem. The data needs to be cleaned before it can be used to answer the questions we have. Since each observation has the various statistics for each group, it would be easier if the age were to have their own column (as a factor), so each row would have state, year, age, pregnancy rate, abortion rate, birth rate, abortion ratio, number of pregnancies, miscarriages, abortions, births and the population of women for that age group. Roe v. Wade can be said to be mainly characterized by a person’s political affiliation i.e. Republicans are against abortion, while Democrats support making abortion accesible to all women. Thus, there is a need to include the political affiliation of each state. Another dataset can be created, which contains the state and its political affiliation i.e whether it is a Republican or Democrat state. There are also some overlaps in data for the age groups since less than 20 includes less than 15, 15 - 17 and 18 - 19. There is also 15 - 19, which includes 15 - 17 and 18 - 19. Since 15 - 19 contains the necessary data and follows the same pattern as other age groups such as 20 - 24, information for 15 - 17 and 18 - 19, along with less than 20 age groups can be removed. The main questions are: 1) How does the state’s party affiliation affect the abortion rates i.e. does Republican states have a lower abortion rate? 2) How has teen pregnancy and abortion rates changed over the years?

[1] “About”. guttmacher.org. https://www.guttmacher.org/about (accessed Oct 12, 2022)
[2] I. Maddow-Zimet and K. Kost. “Pregnancies, Births and Abortions in the United States, 1973–2017: National and State Trends by Age”. guttmacher.org. https://www.guttmacher.org/report/pregnancies-births-abortions-in-united-states-1973-2017 (accessed Oct. 12, 2022)
[3] I. Maddow-Zimet and K. Kost. “Pregnancies, Births and Abortions in the
United States, 1973–2017: National and State Trends by Age Methodology Appendix”. guttmacher.org. https://www.guttmacher.org/sites/default/files/report_downloads/pregnancies-births-abortions-us-1973-2017-method-appendix.pdf (accessed Oct. 12, 2022)