---
title: Blog Post 8
author: Transformers
date: '2022-12-09'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-12-09T07:38:30-04:00'
featuredVideo: ~
featuredImage: ~
---

## Tentative Thesis: 
* We were interested in investigating the impact of 1) political affiliation and 2) age of childbearer over the years on pregnancy and abortion rates.

# Impact of Political Affiliation
* Based on the limited exploratory data analysis that we have conducted, it seems that pregnancy rate is not impacted by political affiliation, but abortion rate is. This is supported by the graphs 1 and 2 on our analysis page that show Average Pregnancy and Abortion Rate by State Affiliation. On the Abortion rate graph, there is a clear pattern where Democratic states have higher abortion rates as compared to Republican states. However, on the Pregnancy rate graph, this distinction is not as apparent.

# Impact of Age of Childbearer over the Years
* Over the last 30 years, it seems that the pregnancy rate for age groups 15-24 has significantly decreased, while the pregnancy rate for age groups 30-39 have increased. That is, childbearers seems to be getting pregnant later in life in recent years, as compared to teenagers.
* For the abortion rate graph, we noticed an overall increase in abortions between years 1970-1980. This aligns with the legalization of abortion (the Supreme Court ruling of Roe v. Wade) in the US in 1973. After 1990, we notice a decrease in abortion rate for age groups 15-24. 

# Impact of Politcal Affiliation AND Age of Childbearer
* When we integrated the impact of our 2 variables of interest, we noticed that there was no significant difference in pregnancy rate over the years by political affiliation for any age group.
* However, when we did the same for abortion rate, there was a clear difference. That is, we noticed that the a


# Plans to polish our visualizations and tables: 
* Overall, we plan to look through all of our work and standardize our format so that it is consistent and readable for all public users. We will plan to add informative titles, captions, axis labels, etc to make sure our plots are digestable and easily interpretable. For some of our plots, we have utilized the Economist theme from the package, ggthemes to add professional engagement with the audience. We plan to use the theme throughout our website to keep things consistent and professional.
